default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['MYSQL_USER'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  host: localhost


development:
  <<: *default
  database: EnglishTech_development

test:
  <<: *default
  database: EnglishTech_test

production:
  <<: *default
  database: EnglishTech_production
